FROM apache/spark:3.5.0

USER root
RUN pip3 install --no-cache-dir python-dotenv

RUN echo "from pyspark.sql import SparkSession; \
SparkSession.builder \
  .config('spark.jars.packages', 'org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262') \
  .getOrCreate().stop()" | python3 || true

USER spark
