FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc librdkafka-dev openjdk-17-jdk-headless procps default-mysql-client curl ca-certificates && \
    curl -L -o /usr/local/bin/kubectl https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-fab \
    minio \
    chess \
    pandas \
    requests \
    pyspark==3.5.0

ENV SPARK_HOME=/home/airflow/.local/lib/python3.13/site-packages/pyspark
ENV PATH=$PATH:$SPARK_HOME/bin
ENV PYSPARK_PYTHON=python3.13
ENV PYSPARK_DRIVER_PYTHON=python3.13
