apiVersion: v1
kind: ConfigMap
metadata:
  name: chess-config
  namespace: chess
data:
  # MinIO
  MINIO_ENDPOINT: http://minio:9000
  MINIO_BUCKET_DEV: chess-dev
  MINIO_BUCKET_PROD: chess-prod

  # Polaris
  POLARIS_URI: http://polaris:8181/api/catalog
  POLARIS_DB_USER: postgres
  POLARIS_DB_URL: jdbc:postgresql://postgres:5432/polaris_db
  POLARIS_NAMESPACE: prod
  POLARIS_WAREHOUSE: chess_warehouse

  # StarRocks
  STARROCKS_HOST: starrocks-fe
  STARROCKS_PORT: "9030"
  STARROCKS_USER: root

  # Stockfish
  STOCKFISH_URL: http://stockfish:8001/eval
  STOCKFISH_DEPTH: "18"

  # Spark
  AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077
  SPARK_MASTER: spark://spark-master:7077

  # Airflow
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
  AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution
